name: BetterDoors
version: '1.0.0-HOTFIX'
main: org.artaphy.betterDoors.BetterDoors
api-version: '1.21'
load: STARTUP
authors: [ Artaphy ]
description: A plugin that enhances door interactions with knocking, hand-opening, and redstone control.
