name: PR Test

on:
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: gradle/gradle-build-action@v2
      - uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
      - name: Apply Patches and Build
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Actions"
          chmod +x ./gradlew
          ./gradlew clean build
      - uses: actions/upload-artifact@v3
        with:
          name: ArtaphyCore
          path: build/libs/*.jar
